volumes:
  db-data:
  pgadmin-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4111:4111"
    env_file:
      - .env.development
    volumes:
      - .:/app:cached
    entrypoint: /app/docker-entrypoint.sh
    command: tail -f /dev/null
    depends_on:
      - vector-db
  vector-db:
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_database
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:5050"
    volumes:
      - ./pgadmin4-servers.json:/app/servers.json
      - pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=local@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_SERVER_JSON_FILE=/app/servers.json
